### PR TITLE
line break added

### PR DESCRIPTION
**Pull request by v-hearya**

### CODE REVIEW

**Comment by nivnar** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[server-2013/lync-server-2013-create-a-voice-routing-test-case.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-create-a-voice-routing-test-case.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C24%5C8ae1a3e0-442b-f793-6909-428cf7ff95ee%5CPullRequest%5C201808232359366556-26%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=wNLzrkAEPMwgvOba9sG9%2F1wMpVVDHWzOnCUOkzKtFEc%3D&st=2018-08-23T23%3A56%3A48Z&se=2018-09-24T00%3A01%3A48Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nivnar** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[server-2013/lync-server-2013-create-a-voice-routing-test-case.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-create-a-voice-routing-test-case.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-example-of-gathering-your-requirements-for-call-admission-control.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-example-of-gathering-your-requirements-for-call-admission-control.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C24%5C8ae1a3e0-442b-f793-6909-428cf7ff95ee%5CPullRequest%5C201808240002447942-26%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=FJuyEaIkW3eFCv7zwedq3onW1hnrX4ur536cOtByFzw%3D&st=2018-08-23T23%3A59%3A47Z&se=2018-09-24T00%3A04%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nivnar** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[server-2013/lync-server-2013-create-a-voice-routing-test-case.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-create-a-voice-routing-test-case.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-example-of-gathering-your-requirements-for-call-admission-control.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-example-of-gathering-your-requirements-for-call-admission-control.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-user-roles-in-persistent-chat-server.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-user-roles-in-persistent-chat-server.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C24%5C8ae1a3e0-442b-f793-6909-428cf7ff95ee%5CPullRequest%5C201808240004021795-26%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=t31SWb6FdKpNppVHwZpa%2BGiHRRHjJsjjtinUVPziLIQ%3D&st=2018-08-24T00%3A01%3A57Z&se=2018-09-24T00%3A06%3A57Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nivnar** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[server-2013/lync-server-2013-create-a-voice-routing-test-case.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-create-a-voice-routing-test-case.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-example-of-gathering-your-requirements-for-call-admission-control.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-example-of-gathering-your-requirements-for-call-admission-control.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-response-group-disaster-recovery-procedures.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-response-group-disaster-recovery-procedures.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-user-roles-in-persistent-chat-server.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-user-roles-in-persistent-chat-server.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C24%5C8ae1a3e0-442b-f793-6909-428cf7ff95ee%5CPullRequest%5C201808240005296924-26%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=8IH3RS3XMX%2BneyHU6vByNtez7egliHeUHTD3XejkG5Y%3D&st=2018-08-24T00%3A04%3A18Z&se=2018-09-24T00%3A09%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nivnar** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[server-2013/lync-server-2013-create-a-voice-routing-test-case.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-create-a-voice-routing-test-case.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-delegate-setup-permissions.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-delegate-setup-permissions.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-example-of-gathering-your-requirements-for-call-admission-control.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-example-of-gathering-your-requirements-for-call-admission-control.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-hosted-exchange-um-routing.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-hosted-exchange-um-routing.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-response-group-disaster-recovery-procedures.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-response-group-disaster-recovery-procedures.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-user-roles-in-persistent-chat-server.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-user-roles-in-persistent-chat-server.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C24%5C8ae1a3e0-442b-f793-6909-428cf7ff95ee%5CPullRequest%5C201808240009085953-26%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=6cnq4ekEHAIJxfxvjrd1ghK7HZe7iMdaBAyjJCvL%2FBw%3D&st=2018-08-24T00%3A06%3A46Z&se=2018-09-24T00%3A11%3A46Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nivnar** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[server-2013/lync-server-2013-create-a-voice-routing-test-case.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-create-a-voice-routing-test-case.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-delegate-setup-permissions.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-delegate-setup-permissions.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-example-of-gathering-your-requirements-for-call-admission-control.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-example-of-gathering-your-requirements-for-call-admission-control.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-hosted-exchange-um-routing.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-hosted-exchange-um-routing.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-managing-computer-site-and-global-centralized-logging-service-configuration.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-managing-computer-site-and-global-centralized-logging-service-configuration.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-response-group-disaster-recovery-procedures.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-response-group-disaster-recovery-procedures.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-user-roles-in-persistent-chat-server.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-user-roles-in-persistent-chat-server.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C24%5C8ae1a3e0-442b-f793-6909-428cf7ff95ee%5CPullRequest%5C201808240010443119-26%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ar8g%2FwECDClZzbqcb%2Fdn3%2B6L%2Fap%2F3X%2BE47ieLUojR0M%3D&st=2018-08-24T00%3A09%3A03Z&se=2018-09-24T00%3A14%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nivnar** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[server-2013/lync-server-2013-create-a-voice-routing-test-case.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-create-a-voice-routing-test-case.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-define-and-configure-a-front-end-pool-or-standard-edition-server.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-define-and-configure-a-front-end-pool-or-standard-edition-server.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-delegate-setup-permissions.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-delegate-setup-permissions.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-example-of-gathering-your-requirements-for-call-admission-control.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-example-of-gathering-your-requirements-for-call-admission-control.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-hosted-exchange-um-routing.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-hosted-exchange-um-routing.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-managing-computer-site-and-global-centralized-logging-service-configuration.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-managing-computer-site-and-global-centralized-logging-service-configuration.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-response-group-disaster-recovery-procedures.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-response-group-disaster-recovery-procedures.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-user-roles-in-persistent-chat-server.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-user-roles-in-persistent-chat-server.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C24%5C8ae1a3e0-442b-f793-6909-428cf7ff95ee%5CPullRequest%5C201808240012388436-26%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ilrPx3fdtuYxb7%2B%2BUATYXO9WdVwS2JppeUspxox5WDk%3D&st=2018-08-24T00%3A11%3A22Z&se=2018-09-24T00%3A16%3A22Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nivnar** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[server-2013/lync-server-2013-create-a-voice-routing-test-case.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-create-a-voice-routing-test-case.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-define-and-configure-a-front-end-pool-or-standard-edition-server.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-define-and-configure-a-front-end-pool-or-standard-edition-server.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-delegate-setup-permissions.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-delegate-setup-permissions.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-designing-the-sip-trunk-for-e9-1-1.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-designing-the-sip-trunk-for-e9-1-1.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-example-of-gathering-your-requirements-for-call-admission-control.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-example-of-gathering-your-requirements-for-call-admission-control.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-front-end-pool-abc-failover-procedure.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-front-end-pool-abc-failover-procedure.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-hosted-exchange-um-routing.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-hosted-exchange-um-routing.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-managing-computer-site-and-global-centralized-logging-service-configuration.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-managing-computer-site-and-global-centralized-logging-service-configuration.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-response-group-disaster-recovery-procedures.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-response-group-disaster-recovery-procedures.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-user-roles-in-persistent-chat-server.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-user-roles-in-persistent-chat-server.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C24%5C8ae1a3e0-442b-f793-6909-428cf7ff95ee%5CPullRequest%5C201808240014359071-26%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=lHNwdjBOhENYM83rW3dGVLvS6wn1lhNr2j9%2Fyc8Ljyw%3D&st=2018-08-24T00%3A13%3A36Z&se=2018-09-24T00%3A18%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nivnar** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[server-2013/lync-server-2013-configure-web-publishing-rules-for-a-single-internal-pool.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-configure-web-publishing-rules-for-a-single-internal-pool.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-create-a-voice-routing-test-case.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-create-a-voice-routing-test-case.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-define-and-configure-a-front-end-pool-or-standard-edition-server.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-define-and-configure-a-front-end-pool-or-standard-edition-server.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-delegate-setup-permissions.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-delegate-setup-permissions.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-designing-the-sip-trunk-for-e9-1-1.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-designing-the-sip-trunk-for-e9-1-1.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-example-of-gathering-your-requirements-for-call-admission-control.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-example-of-gathering-your-requirements-for-call-admission-control.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-front-end-pool-abc-failover-procedure.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-front-end-pool-abc-failover-procedure.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-hosted-exchange-um-routing.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-hosted-exchange-um-routing.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-managing-computer-site-and-global-centralized-logging-service-configuration.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-managing-computer-site-and-global-centralized-logging-service-configuration.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-response-group-disaster-recovery-procedures.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-response-group-disaster-recovery-procedures.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-user-roles-in-persistent-chat-server.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-user-roles-in-persistent-chat-server.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C24%5C8ae1a3e0-442b-f793-6909-428cf7ff95ee%5CPullRequest%5C201808240017490027-26%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=zG%2FHVVQ600zPhoZSvHwRWDq%2FGBNBlPwAckpt2tFs0QI%3D&st=2018-08-24T00%3A15%3A58Z&se=2018-09-24T00%3A20%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nivnar** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[server-2013/lync-server-2013-configure-web-publishing-rules-for-a-single-internal-pool.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-configure-web-publishing-rules-for-a-single-internal-pool.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-configuring-video-bandwidth.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-configuring-video-bandwidth.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-create-a-voice-routing-test-case.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-create-a-voice-routing-test-case.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-define-and-configure-a-front-end-pool-or-standard-edition-server.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-define-and-configure-a-front-end-pool-or-standard-edition-server.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-delegate-setup-permissions.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-delegate-setup-permissions.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-designing-the-sip-trunk-for-e9-1-1.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-designing-the-sip-trunk-for-e9-1-1.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-example-of-gathering-your-requirements-for-call-admission-control.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-example-of-gathering-your-requirements-for-call-admission-control.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-front-end-pool-abc-failover-procedure.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-front-end-pool-abc-failover-procedure.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-hosted-exchange-um-routing.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-hosted-exchange-um-routing.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-managing-computer-site-and-global-centralized-logging-service-configuration.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-managing-computer-site-and-global-centralized-logging-service-configuration.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-response-group-disaster-recovery-procedures.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-response-group-disaster-recovery-procedures.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-user-roles-in-persistent-chat-server.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.fr-fr/blob/master/server-2013/lync-server-2013-user-roles-in-persistent-chat-server.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C24%5C8ae1a3e0-442b-f793-6909-428cf7ff95ee%5CPullRequest%5C201808240019446266-26%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=b0CX2Jrgc9D2a7IDDAc9%2BHaPEpexpIXReASJQVyctRk%3D&st=2018-08-24T00%3A18%3A06Z&se=2018-09-24T00%3A23%3A06Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Review by DanMSFT — APPROVED** [review]

**Review by DanMSFT — APPROVED** [review]

**Pull request merged**
